### PR TITLE
Documentation cleaning and minor fixes

### PR DESCRIPTION
**Pull request by mippersiel**
- Added 'auth_opt_' to all configuration elements
- Removed all tabs
- Fixed indentations in tables
- Fixed minor errors in javascript section and added link to Go otto
- Added example scripts in javacript section
- Added examples in HTTP section for JSON queries

### CODE REVIEW

**Comment by iegomez** [comment]
Sorry, I was on vacation and work's been brutal since I came back.
I'll take a look as soon as I can.

**Comment by iegomez** [comment]
He, after checking it, I'm a bit conflicted with this PR: it happens that I do prefer tabs over spaces (shit, flame wars incoming, at least one of my coworkers would want to punch me, but he's on vacation right now). :sweat_smile:

**Comment by mippersiel** [comment]
:laughing: No worries at all, I'll do the update from spaces to tabs. As for the contents, it looks good?

**Comment by iegomez** [comment]
He, it was just a joke while I was going over issues and PRs last night.
I'll take a better look today. 😉

**Review by iegomez — APPROVED** [review]

**Pull request merged**
