### PR TITLE
update test tools

### PR DESCRIPTION
**Pull request by sseide**
for easier comparison of pbkdf2 hash i added a new commad line tool using your library functions.
Hope it helps or may be usefull in it self for some shell scripting

* add cli tool to compare password with pbkdf2 hash
* allow setting keylwght on generating new hash with pw cli tool

### CODE REVIEW

**Comment by iegomez** [comment]
Hi, thanks for the PR. I like the addition of the user definable `salt` length, but I'd refactor the tool to look something like this:
```go
func main() {

	var password = flag.String("p", "", "plain text password")
	var hashed = flag.String("h", "", "pbkdf2 password hash")

	flag.Parse()

	if common.HashCompare(*password, *hashed) {
		fmt.Println("success: plain and hashed passwords match")
		return
	}
	fmt.Println("error: plain and hashed passwords don't match")
}
```
If you can add those changes and a mention on the README's section for the `pw` tool, I'll merge it.

**Comment by sseide** [comment]
Ok, code updated.

But i'd like to leave a non-zero exit code if password does not match for easier scripting usage. Only have to compare exit code than instead of text parsing....

**Comment by iegomez** [comment]
Hi, sorry for the delay. I think the requirement is a bit too specific to be included with the more general plugin, so I created a separate repo that calls the `common` package here: https://github.com/iegomez/pw-test.

So, if you'd like to remove the test utility part and leave only the ability to change the salt size, I'll merge this. It'd be nice to also include a link to the testing tool and maybe improve a bit the docs regarding the usage of `pw` at this section https://github.com/iegomez/mosquitto-go-auth#files.

Let me know if you'd be interested in adding that.

Cheers!

**Comment by iegomez** [comment]
@sseide Any news on this? I'm asking to manually add the salt size changes if you're not interested.

**Comment by sseide** [comment]
Sorry, to much to do right now.  and have not found time to check for pbkdf2 differences either...  But if you only want to add salt param its problably faster to add this one param manually.

**Comment by iegomez** [comment]
I've just added the `saltSize` flag and comments at the Readme. Thanks again for bringing this up.

Cheers!

**Pull request closed without merging**
