### PR TITLE
example ACL values & working mysql query

### PR DESCRIPTION
**Pull request by simonfongnt**
added example ACL values as for permission.
updated working mysql ACL query for Testing example.

### CODE REVIEW

**Comment by iegomez** [comment]
Hi, @simonfongnt, and thanks for your interest!

I wanna clarify a couple of things:
- The values are not _bitwise_ (isn't that and adjective for operators?), they are just `ints` that happen to be expressed in their `hex` form.
- A read/write permissions should not be `0x05`, **it might be** if it suits what you want from the query. In fact, there's no rule to how you build your queries, you just need to know what value Mosquitto will pass depending on the access request, e.g. `4` (or `0x04`) for `subscribe`. Then you may achieve whatever goal you want in ACL checks by either tweaking the query or the records.

**Comment by simonfongnt** [comment]
@iegomez thanks for the feedback and I am sorry bothering you during your busy month. 

- I shall call it `binary flag` instead of `bitwise` but I am not convinced they are just happened to be in `hex` form.
- `0x05` should have read/subscription permission, `0x03` has read/write permission and `0x07` has all permissions and i had tested these.

if this is not the case, we may start over from issue and discuss it when you are available.

**Comment by simonfongnt** [comment]
@iegomez after some digging in this and mosquitto projects, i can't find anything to support my binary flag statement. 
i suppose you are correct that it just happens to my query with `&` operator could have both read/subscription permission. 
i shall check again why my readonly ACL wasn't working before.
sorry to disturb you and please remove this pull request.

**Comment by iegomez** [comment]
@simonfongnt No worries, you're not bothering at all! 
And as said, that may work, it's just not mandatory to use bitwise operations for auth.

Have a great end of year!

**Pull request closed without merging**
