### PR TITLE
Updated README

### PR DESCRIPTION
**Pull request by albertogeniola**
Added GO installation instructions

### CODE REVIEW

**Comment by iegomez** [comment]
Hey, @albertogeniola! Thanks for your contribution.

I think if we want to bump up the versions we could use Mosquito 2.x.y. Also, the plugin doesn't depend on Go's 1.13 version, I'm pretty sure it runs fine with latest, though I haven't tried in a couple of weeks.

**Comment by albertogeniola** [comment]
> Hey, @albertogeniola! Thanks for your contribution.
> 
> I think if we want to bump up the versions we could use Mosquito 2.x.y. Also, the plugin doesn't depend on Go's 1.13 version, I'm pretty sure it runs fine with latest, though I haven't tried in a couple of weeks.

Hi @iegomez ,
yeah, 1.13 is not mandatory. I've just picked that one as versions lower than that failed (due to missing TLS1.3). Which version would you advice to pin? I can test it and report back to you.
Also, I'm currently using mosquitto 2.0.9, so I agree we can bump that as well.

**Comment by iegomez** [comment]
@albertogeniola maybe instead of pinning a version in instructions, you can just link to Go's download page: https://golang.org/dl/

**Comment by albertogeniola** [comment]
In my opinion (and experience), we should at least specify or pin a minimum GO version. The reason why I started this PR is that: the installation instructions tells you to install go and so I did. However, after building problems, I realized that the go version was not recent enough: as soon as I updated go to 1.13, I was able to build. 

If you agree, I'd add some comments to the README to make users print the Go version and tell to update to minimum version 1.13 (via Go download website) if the installed version is older than that. Would this work for you?

**Review by albertogeniola — COMMENTED** [review]
@iegomez : I've updated the instructions to point to the official Go download page. I've also bumped up the Go installed version to 1.16.

**Comment by iegomez** [comment]
@albertogeniola My point was more about just linking to the official page instead of setting a specific version in the README, I absolutely agree about stating what's the minimum supported version.

**Review by iegomez — APPROVED** [review]

**Pull request merged**
