### PR TITLE
Add Docker image to run tests

### PR DESCRIPTION
**Pull request by PierreF**
To run tests (which requires lots of backends), I've used Docker containers.
This PR add steps to rebuild and run test using this Docker image.

It's probably not prefect (sometime Redis cluster fail... not every run) but it allow me to run the tests.

### CODE REVIEW

**Comment by iegomez** [comment]
Hi, @PierreF! Thanks so much for this, I've been meaning to add something similar but never found the time. I won't be able to review it properly until next week since I won't have my dev machine during the weekend, but I'll take a look as soon as possible.

**Comment by PierreF** [comment]
That's fine for me, thank for the query reply.

**Review by iegomez — COMMENTED** [review]
Wait, isn't this missing `sqlite3` dependency? How is it passing? :thinking:

**Comment by PierreF** [comment]
It's the same as base Dockerfile (just the end that change).

https://github.com/mattn/go-sqlite3 seems to bundle sqlite3 code in its repository (sqlite3-binding.c), which means sqlite3 get bundled in both source code and then in binary (static linking).

**Comment by iegomez** [comment]
Oh, interesting! TIL.

**Review by iegomez — APPROVED** [review]

**Pull request merged**
